import React, { createContext, useContext, useState } from 'react'

export const LANGUAGES = {
  es: { name: 'Español',    flag: '🇦🇷' },
  en: { name: 'English',    flag: '🇺🇸' },
  pt: { name: 'Português',  flag: '🇧🇷' },
  fr: { name: 'Français',   flag: '🇫🇷' },
  de: { name: 'Deutsch',    flag: '🇩🇪' },
  it: { name: 'Italiano',   flag: '🇮🇹' },
  zh: { name: '中文',        flag: '🇨🇳' },
  ja: { name: '日本語',      flag: '🇯🇵' },
  ar: { name: 'العربية',    flag: '🇸🇦' },
  ko: { name: '한국어',      flag: '🇰🇷' },
  ru: { name: 'Русский',    flag: '🇷🇺' },
  nl: { name: 'Nederlands', flag: '🇳🇱' },
  pl: { name: 'Polski',     flag: '🇵🇱' },
  tr: { name: 'Türkçe',    flag: '🇹🇷' },
  hi: { name: 'हिन्दी',     flag: '🇮🇳' },
  sv: { name: 'Svenska',    flag: '🇸🇪' },
  no: { name: 'Norsk',      flag: '🇳🇴' },
  da: { name: 'Dansk',      flag: '🇩🇰' },
  fi: { name: 'Suomi',      flag: '🇫🇮' },
  el: { name: 'Ελληνικά',  flag: '🇬🇷' },
  he: { name: 'עברית',      flag: '🇮🇱' },
  ro: { name: 'Română',     flag: '🇷🇴' },
  cs: { name: 'Čeština',   flag: '🇨🇿' },
  hu: { name: 'Magyar',     flag: '🇭🇺' },
}

const T = {
  es: {
    'nav.sales':'Ventas','nav.products':'Productos','nav.history':'Historial',
    'nav.board':'Tablero','nav.ai':'Análisis IA','nav.calendar':'Calendario','nav.settings':'Configuración',
    'app.yourbiz':'Tu negocio','app.logout':'Cerrar sesión','app.version':'Your Business v1.2.1',
    'settings.title':'Configuración','settings.appearance':'Apariencia','settings.theme':'Tema de la interfaz',
    'settings.dark':'🌙 Oscuro','settings.light':'☀️ Claro','settings.language':'Idioma',
    'settings.language_label':'Idioma de la app',
    'settings.business':'Mi negocio','settings.businessName':'Nombre del negocio',
    'settings.saveName':'Guardar nombre','settings.saving':'Guardando...',
    'settings.changePass':'Cambiar contraseña','settings.currentPass':'Contraseña actual',
    'settings.newPass':'Nueva contraseña','settings.confirmPass':'Confirmar nueva',
    'settings.changePassBtn':'Cambiar contraseña',
    'settings.changeEmail':'Cambiar correo electrónico','settings.currentEmail':'Correo actual',
    'settings.newEmail':'Nuevo correo','settings.changeEmailBtn':'Cambiar correo',
    'settings.aiApi':'Análisis IA — API Key',
    'settings.privacy':'Privacidad','settings.telemetry':'Datos de uso anónimos',
    'settings.telOn':'Activada','settings.telOff':'Desactivada',
    'settings.data':'Datos','settings.exportToday':'Exportar ventas de hoy','settings.downloadCsv':'⬇ Descargar CSV',
    'sales.search':'Buscar producto...','sales.cart':'Carrito','sales.total':'Total',
    'sales.checkout':'Confirmar venta','sales.empty':'Seleccioná productos','sales.registered':'Orden #',
    'history.title':'Historial del día','history.total':'Total vendido','history.orders':'Órdenes',
    'history.order':'Orden','history.products':'Productos',
    'board.title':'Tablero de pedidos','board.empty':'Sin pedidos pendientes',
    'board.markDone':'Marcar como listo','board.done':'✓ Listo',
    'board.order':'Orden #',
    'calendar.title':'Calendario','calendar.pickDay':'Seleccioná un día para ver sus datos',
    'calendar.totalSold':'Total vendido','calendar.orders':'Órdenes','calendar.noSales':'Sin ventas este día',
    'calendar.notes':'Notas','calendar.notesPlaceholder':'Anotá algo sobre este día...',
    'calendar.aiAnalysis':'Análisis IA del día','calendar.analyzeBtn':'Analizar con IA',
    'calendar.analyzing':'Analizando...','calendar.today':'Hoy',
    'calendar.daysWithSales':'Días con ventas',
    'ai.title':'Análisis IA','ai.today':'hoy','ai.incomeToday':'ingresos hoy',
    'ai.salesToday':'Ventas hoy','ai.bestDay':'Mejor día','ai.topProduct':'Prod. estrella',
    'ai.topProducts':'Top productos más vendidos',
    'common.save':'Guardar','common.cancel':'Cancelar','common.delete':'Eliminar',
    'common.loading':'Cargando...','common.error':'Error','common.ok':'Aceptar',
    'common.show':'Ver','common.hide':'Ocultar',
    'consent.title':'Ayudanos a mejorar Your Business',
    'consent.desc':'Recopilamos datos anónimos de uso (qué funciones se usan y con qué frecuencia) para mejorar la app. Nunca enviamos tu nombre, productos ni montos. Podés desactivarlo en Configuración en cualquier momento.',
    'consent.accept':'Aceptar','consent.reject':'No, gracias',
  },
  en: {
    'nav.sales':'Sales','nav.products':'Products','nav.history':'History',
    'nav.board':'Board','nav.ai':'AI Analysis','nav.calendar':'Calendar','nav.settings':'Settings',
    'app.yourbiz':'Your business','app.logout':'Sign out','app.version':'Your Business v1.2.1',
    'settings.title':'Settings','settings.appearance':'Appearance','settings.theme':'Interface theme',
    'settings.dark':'🌙 Dark','settings.light':'☀️ Light','settings.language':'Language',
    'settings.language_label':'App language',
    'settings.business':'My business','settings.businessName':'Business name',
    'settings.saveName':'Save name','settings.saving':'Saving...',
    'settings.changePass':'Change password','settings.currentPass':'Current password',
    'settings.newPass':'New password','settings.confirmPass':'Confirm new',
    'settings.changePassBtn':'Change password',
    'settings.changeEmail':'Change email address','settings.currentEmail':'Current email',
    'settings.newEmail':'New email','settings.changeEmailBtn':'Change email',
    'settings.aiApi':'AI Analysis — API Key',
    'settings.privacy':'Privacy','settings.telemetry':'Anonymous usage data',
    'settings.telOn':'Enabled','settings.telOff':'Disabled',
    'settings.data':'Data','settings.exportToday':"Export today's sales",'settings.downloadCsv':'⬇ Download CSV',
    'sales.search':'Search product...','sales.cart':'Cart','sales.total':'Total',
    'sales.checkout':'Confirm sale','sales.empty':'Select products','sales.registered':'Order #',
    'history.title':"Today's history",'history.total':'Total sold','history.orders':'Orders',
    'history.order':'Order','history.products':'Products',
    'board.title':'Order board','board.empty':'No pending orders',
    'board.markDone':'Mark as done','board.done':'✓ Done',
    'board.order':'Order #',
    'calendar.title':'Calendar','calendar.pickDay':'Select a day to view its data',
    'calendar.totalSold':'Total sold','calendar.orders':'Orders','calendar.noSales':'No sales this day',
    'calendar.notes':'Notes','calendar.notesPlaceholder':'Write something about this day...',
    'calendar.aiAnalysis':'AI analysis for the day','calendar.analyzeBtn':'Analyze with AI',
    'calendar.analyzing':'Analyzing...','calendar.today':'Today',
    'calendar.daysWithSales':'Days with sales',
    'ai.title':'AI Analysis','ai.today':'today','ai.incomeToday':'income today',
    'ai.salesToday':'Sales today','ai.bestDay':'Best day','ai.topProduct':'Top product',
    'ai.topProducts':'Top selling products',
    'common.save':'Save','common.cancel':'Cancel','common.delete':'Delete',
    'common.loading':'Loading...','common.error':'Error','common.ok':'OK',
    'common.show':'Show','common.hide':'Hide',
    'consent.title':'Help us improve Your Business',
    'consent.desc':'We collect anonymous usage data (which features are used and how often) to improve the app. We never send your name, products, or amounts. You can disable it in Settings at any time.',
    'consent.accept':'Accept','consent.reject':'No, thanks',
  },
  pt: {
    'nav.sales':'Vendas','nav.products':'Produtos','nav.history':'Histórico',
    'nav.board':'Quadro','nav.ai':'Análise IA','nav.calendar':'Calendário','nav.settings':'Configurações',
    'app.yourbiz':'Seu negócio','app.logout':'Sair','app.version':'Your Business v1.2.1',
    'settings.title':'Configurações','settings.appearance':'Aparência','settings.theme':'Tema da interface',
    'settings.dark':'🌙 Escuro','settings.light':'☀️ Claro','settings.language':'Idioma',
    'settings.language_label':'Idioma do aplicativo',
    'settings.business':'Meu negócio','settings.businessName':'Nome do negócio',
    'settings.saveName':'Salvar nome','settings.saving':'Salvando...',
    'settings.changePass':'Alterar senha','settings.currentPass':'Senha atual',
    'settings.newPass':'Nova senha','settings.confirmPass':'Confirmar nova',
    'settings.changePassBtn':'Alterar senha',
    'settings.changeEmail':'Alterar e-mail','settings.currentEmail':'E-mail atual',
    'settings.newEmail':'Novo e-mail','settings.changeEmailBtn':'Alterar e-mail',
    'settings.aiApi':'Análise IA — API Key',
    'settings.privacy':'Privacidade','settings.telemetry':'Dados de uso anônimos',
    'settings.telOn':'Ativado','settings.telOff':'Desativado',
    'settings.data':'Dados','settings.exportToday':'Exportar vendas de hoje','settings.downloadCsv':'⬇ Baixar CSV',
    'sales.search':'Buscar produto...','sales.cart':'Carrinho','sales.total':'Total',
    'sales.checkout':'Confirmar venda','sales.empty':'Selecione produtos','sales.registered':'Pedido #',
    'history.title':'Histórico do dia','history.total':'Total vendido','history.orders':'Pedidos',
    'history.order':'Pedido','history.products':'Produtos',
    'board.title':'Quadro de pedidos','board.empty':'Sem pedidos pendentes',
    'board.markDone':'Marcar como pronto','board.done':'✓ Pronto',
    'board.order':'Pedido #',
    'calendar.title':'Calendário','calendar.pickDay':'Selecione um dia para ver os dados',
    'calendar.totalSold':'Total vendido','calendar.orders':'Pedidos','calendar.noSales':'Sem vendas neste dia',
    'calendar.notes':'Notas','calendar.notesPlaceholder':'Anote algo sobre este dia...',
    'calendar.aiAnalysis':'Análise IA do dia','calendar.analyzeBtn':'Analisar com IA',
    'calendar.analyzing':'Analisando...','calendar.today':'Hoje',
    'calendar.daysWithSales':'Dias com vendas',
    'ai.title':'Análise IA','ai.today':'hoje','ai.incomeToday':'receita hoje',
    'ai.salesToday':'Vendas hoje','ai.bestDay':'Melhor dia','ai.topProduct':'Top produto',
    'ai.topProducts':'Produtos mais vendidos',
    'common.save':'Salvar','common.cancel':'Cancelar','common.delete':'Excluir',
    'common.loading':'Carregando...','common.error':'Erro','common.ok':'OK',
    'common.show':'Ver','common.hide':'Ocultar',
    'consent.title':'Ajude-nos a melhorar o Your Business',
    'consent.desc':'Coletamos dados anônimos de uso para melhorar o aplicativo. Nunca enviamos seu nome, produtos ou valores.',
    'consent.accept':'Aceitar','consent.reject':'Não, obrigado',
  },
  fr: {
    'nav.sales':'Ventes','nav.products':'Produits','nav.history':'Historique',
    'nav.board':'Tableau','nav.ai':'Analyse IA','nav.calendar':'Calendrier','nav.settings':'Paramètres',
    'app.yourbiz':'Votre entreprise','app.logout':'Déconnexion','app.version':'Your Business v1.2.1',
    'settings.title':'Paramètres','settings.appearance':'Apparence','settings.theme':'Thème de l\'interface',
    'settings.dark':'🌙 Sombre','settings.light':'☀️ Clair','settings.language':'Langue',
    'settings.language_label':'Langue de l\'application',
    'settings.business':'Mon entreprise','settings.businessName':'Nom de l\'entreprise',
    'settings.saveName':'Enregistrer','settings.saving':'Enregistrement...',
    'settings.changePass':'Changer le mot de passe','settings.currentPass':'Mot de passe actuel',
    'settings.newPass':'Nouveau mot de passe','settings.confirmPass':'Confirmer le nouveau',
    'settings.changePassBtn':'Changer le mot de passe',
    'settings.changeEmail':'Changer l\'adresse e-mail','settings.currentEmail':'E-mail actuel',
    'settings.newEmail':'Nouvel e-mail','settings.changeEmailBtn':'Changer l\'e-mail',
    'settings.aiApi':'Analyse IA — Clé API',
    'settings.privacy':'Confidentialité','settings.telemetry':'Données d\'utilisation anonymes',
    'settings.telOn':'Activé','settings.telOff':'Désactivé',
    'settings.data':'Données','settings.exportToday':'Exporter les ventes d\'aujourd\'hui','settings.downloadCsv':'⬇ Télécharger CSV',
    'sales.search':'Rechercher un produit...','sales.cart':'Panier','sales.total':'Total',
    'sales.checkout':'Confirmer la vente','sales.empty':'Sélectionner des produits','sales.registered':'Commande #',
    'history.title':'Historique du jour','history.total':'Total vendu','history.orders':'Commandes',
    'history.order':'Commande','history.products':'Produits',
    'board.title':'Tableau des commandes','board.empty':'Aucune commande en attente',
    'board.markDone':'Marquer comme prêt','board.done':'✓ Prêt',
    'board.order':'Commande #',
    'calendar.title':'Calendrier','calendar.pickDay':'Sélectionnez un jour pour voir les données',
    'calendar.totalSold':'Total vendu','calendar.orders':'Commandes','calendar.noSales':'Aucune vente ce jour',
    'calendar.notes':'Notes','calendar.notesPlaceholder':'Notez quelque chose sur ce jour...',
    'calendar.aiAnalysis':'Analyse IA du jour','calendar.analyzeBtn':'Analyser avec l\'IA',
    'calendar.analyzing':'Analyse en cours...','calendar.today':'Aujourd\'hui',
    'calendar.daysWithSales':'Jours avec ventes',
    'ai.title':'Analyse IA','ai.today':'aujourd\'hui','ai.incomeToday':'revenus aujourd\'hui',
    'ai.salesToday':'Ventes aujourd\'hui','ai.bestDay':'Meilleur jour','ai.topProduct':'Top produit',
    'ai.topProducts':'Produits les plus vendus',
    'common.save':'Enregistrer','common.cancel':'Annuler','common.delete':'Supprimer',
    'common.loading':'Chargement...','common.error':'Erreur','common.ok':'OK',
    'common.show':'Voir','common.hide':'Masquer',
    'consent.title':'Aidez-nous à améliorer Your Business',
    'consent.desc':'Nous collectons des données d\'utilisation anonymes pour améliorer l\'application.',
    'consent.accept':'Accepter','consent.reject':'Non, merci',
  },
  de: {
    'nav.sales':'Verkauf','nav.products':'Produkte','nav.history':'Verlauf',
    'nav.board':'Tafel','nav.ai':'KI-Analyse','nav.calendar':'Kalender','nav.settings':'Einstellungen',
    'app.yourbiz':'Ihr Unternehmen','app.logout':'Abmelden','app.version':'Your Business v1.2.1',
    'settings.title':'Einstellungen','settings.appearance':'Erscheinungsbild','settings.theme':'Interface-Thema',
    'settings.dark':'🌙 Dunkel','settings.light':'☀️ Hell','settings.language':'Sprache',
    'settings.language_label':'App-Sprache',
    'settings.business':'Mein Unternehmen','settings.businessName':'Unternehmensname',
    'settings.saveName':'Namen speichern','settings.saving':'Speichern...',
    'settings.changePass':'Passwort ändern','settings.currentPass':'Aktuelles Passwort',
    'settings.newPass':'Neues Passwort','settings.confirmPass':'Neues bestätigen',
    'settings.changePassBtn':'Passwort ändern',
    'settings.changeEmail':'E-Mail-Adresse ändern','settings.currentEmail':'Aktuelle E-Mail',
    'settings.newEmail':'Neue E-Mail','settings.changeEmailBtn':'E-Mail ändern',
    'settings.aiApi':'KI-Analyse — API-Schlüssel',
    'settings.privacy':'Datenschutz','settings.telemetry':'Anonyme Nutzungsdaten',
    'settings.telOn':'Aktiviert','settings.telOff':'Deaktiviert',
    'settings.data':'Daten','settings.exportToday':'Heutige Verkäufe exportieren','settings.downloadCsv':'⬇ CSV herunterladen',
    'sales.search':'Produkt suchen...','sales.cart':'Warenkorb','sales.total':'Gesamt',
    'sales.checkout':'Verkauf bestätigen','sales.empty':'Produkte auswählen','sales.registered':'Bestellung #',
    'history.title':'Tageshistorie','history.total':'Gesamtverkauf','history.orders':'Bestellungen',
    'history.order':'Bestellung','history.products':'Produkte',
    'board.title':'Bestelltafel','board.empty':'Keine ausstehenden Bestellungen',
    'board.markDone':'Als erledigt markieren','board.done':'✓ Fertig',
    'board.order':'Bestellung #',
    'calendar.title':'Kalender','calendar.pickDay':'Tag auswählen, um Daten anzuzeigen',
    'calendar.totalSold':'Gesamtverkauf','calendar.orders':'Bestellungen','calendar.noSales':'Keine Verkäufe an diesem Tag',
    'calendar.notes':'Notizen','calendar.notesPlaceholder':'Notiz für diesen Tag...',
    'calendar.aiAnalysis':'KI-Analyse des Tages','calendar.analyzeBtn':'Mit KI analysieren',
    'calendar.analyzing':'Analysiere...','calendar.today':'Heute',
    'calendar.daysWithSales':'Tage mit Verkäufen',
    'ai.title':'KI-Analyse','ai.today':'heute','ai.incomeToday':'Einnahmen heute',
    'ai.salesToday':'Verkäufe heute','ai.bestDay':'Bester Tag','ai.topProduct':'Top-Produkt',
    'ai.topProducts':'Meistverkaufte Produkte',
    'common.save':'Speichern','common.cancel':'Abbrechen','common.delete':'Löschen',
    'common.loading':'Laden...','common.error':'Fehler','common.ok':'OK',
    'common.show':'Anzeigen','common.hide':'Verbergen',
    'consent.title':'Helfen Sie uns, Your Business zu verbessern',
    'consent.desc':'Wir erfassen anonyme Nutzungsdaten, um die App zu verbessern.',
    'consent.accept':'Akzeptieren','consent.reject':'Nein, danke',
  },
  it: {
    'nav.sales':'Vendite','nav.products':'Prodotti','nav.history':'Cronologia',
    'nav.board':'Bacheca','nav.ai':'Analisi IA','nav.calendar':'Calendario','nav.settings':'Impostazioni',
    'app.yourbiz':'La tua attività','app.logout':'Esci','app.version':'Your Business v1.2.1',
    'settings.title':'Impostazioni','settings.appearance':'Aspetto','settings.theme':'Tema interfaccia',
    'settings.dark':'🌙 Scuro','settings.light':'☀️ Chiaro','settings.language':'Lingua',
    'settings.language_label':'Lingua dell\'app',
    'settings.business':'La mia attività','settings.businessName':'Nome dell\'attività',
    'settings.saveName':'Salva nome','settings.saving':'Salvataggio...',
    'settings.changePass':'Cambia password','settings.currentPass':'Password attuale',
    'settings.newPass':'Nuova password','settings.confirmPass':'Conferma nuova',
    'settings.changePassBtn':'Cambia password',
    'settings.changeEmail':'Cambia email','settings.currentEmail':'Email attuale',
    'settings.newEmail':'Nuova email','settings.changeEmailBtn':'Cambia email',
    'settings.aiApi':'Analisi IA — Chiave API',
    'settings.privacy':'Privacy','settings.telemetry':'Dati di utilizzo anonimi',
    'settings.telOn':'Attivato','settings.telOff':'Disattivato',
    'settings.data':'Dati','settings.exportToday':'Esporta vendite di oggi','settings.downloadCsv':'⬇ Scarica CSV',
    'sales.search':'Cerca prodotto...','sales.cart':'Carrello','sales.total':'Totale',
    'sales.checkout':'Conferma vendita','sales.empty':'Seleziona prodotti','sales.registered':'Ordine #',
    'history.title':'Storico del giorno','history.total':'Totale venduto','history.orders':'Ordini',
    'history.order':'Ordine','history.products':'Prodotti',
    'board.title':'Bacheca ordini','board.empty':'Nessun ordine in attesa',
    'board.markDone':'Segna come fatto','board.done':'✓ Fatto',
    'board.order':'Ordine #',
    'calendar.title':'Calendario','calendar.pickDay':'Seleziona un giorno per vedere i dati',
    'calendar.totalSold':'Totale venduto','calendar.orders':'Ordini','calendar.noSales':'Nessuna vendita questo giorno',
    'calendar.notes':'Note','calendar.notesPlaceholder':'Scrivi qualcosa su questo giorno...',
    'calendar.aiAnalysis':'Analisi IA del giorno','calendar.analyzeBtn':'Analizza con IA',
    'calendar.analyzing':'Analisi in corso...','calendar.today':'Oggi',
    'calendar.daysWithSales':'Giorni con vendite',
    'ai.title':'Analisi IA','ai.today':'oggi','ai.incomeToday':'entrate oggi',
    'ai.salesToday':'Vendite oggi','ai.bestDay':'Giorno migliore','ai.topProduct':'Top prodotto',
    'ai.topProducts':'Prodotti più venduti',
    'common.save':'Salva','common.cancel':'Annulla','common.delete':'Elimina',
    'common.loading':'Caricamento...','common.error':'Errore','common.ok':'OK',
    'common.show':'Mostra','common.hide':'Nascondi',
    'consent.title':'Aiutaci a migliorare Your Business',
    'consent.desc':'Raccogliamo dati anonimi di utilizzo per migliorare l\'app.',
    'consent.accept':'Accetta','consent.reject':'No, grazie',
  },
  zh: {
    'nav.sales':'销售','nav.products':'产品','nav.history':'历史',
    'nav.board':'看板','nav.ai':'AI分析','nav.calendar':'日历','nav.settings':'设置',
    'app.yourbiz':'我的业务','app.logout':'退出登录','app.version':'Your Business v1.2.1',
    'settings.title':'设置','settings.appearance':'外观','settings.theme':'界面主题',
    'settings.dark':'🌙 深色','settings.light':'☀️ 浅色','settings.language':'语言',
    'settings.language_label':'应用语言',
    'settings.business':'我的业务','settings.businessName':'业务名称',
    'settings.saveName':'保存名称','settings.saving':'保存中...',
    'settings.changePass':'更改密码','settings.currentPass':'当前密码',
    'settings.newPass':'新密码','settings.confirmPass':'确认新密码',
    'settings.changePassBtn':'更改密码',
    'settings.changeEmail':'更改邮箱','settings.currentEmail':'当前邮箱',
    'settings.newEmail':'新邮箱','settings.changeEmailBtn':'更改邮箱',
    'settings.aiApi':'AI分析 — API密钥',
    'settings.privacy':'隐私','settings.telemetry':'匿名使用数据',
    'settings.telOn':'已启用','settings.telOff':'已禁用',
    'settings.data':'数据','settings.exportToday':'导出今日销售','settings.downloadCsv':'⬇ 下载CSV',
    'sales.search':'搜索产品...','sales.cart':'购物车','sales.total':'合计',
    'sales.checkout':'确认销售','sales.empty':'选择产品','sales.registered':'订单 #',
    'history.title':'今日历史','history.total':'总销售额','history.orders':'订单',
    'history.order':'订单','history.products':'产品',
    'board.title':'订单看板','board.empty':'无待处理订单',
    'board.markDone':'标记为完成','board.done':'✓ 完成',
    'board.order':'订单 #',
    'calendar.title':'日历','calendar.pickDay':'选择一天查看数据',
    'calendar.totalSold':'总销售额','calendar.orders':'订单','calendar.noSales':'当天无销售',
    'calendar.notes':'备注','calendar.notesPlaceholder':'记录这一天的事情...',
    'calendar.aiAnalysis':'当日AI分析','calendar.analyzeBtn':'用AI分析',
    'calendar.analyzing':'分析中...','calendar.today':'今天',
    'calendar.daysWithSales':'有销售的天数',
    'ai.title':'AI分析','ai.today':'今天','ai.incomeToday':'今日收入',
    'ai.salesToday':'今日销售','ai.bestDay':'最佳日','ai.topProduct':'明星产品',
    'ai.topProducts':'最畅销产品',
    'common.save':'保存','common.cancel':'取消','common.delete':'删除',
    'common.loading':'加载中...','common.error':'错误','common.ok':'确定',
    'common.show':'显示','common.hide':'隐藏',
    'consent.title':'帮助我们改进Your Business',
    'consent.desc':'我们收集匿名使用数据以改进应用程序。',
    'consent.accept':'接受','consent.reject':'不，谢谢',
  },
  ja: {
    'nav.sales':'販売','nav.products':'製品','nav.history':'履歴',
    'nav.board':'ボード','nav.ai':'AI分析','nav.calendar':'カレンダー','nav.settings':'設定',
    'app.yourbiz':'マイビジネス','app.logout':'サインアウト','app.version':'Your Business v1.2.1',
    'settings.title':'設定','settings.appearance':'外観','settings.theme':'インターフェーステーマ',
    'settings.dark':'🌙 ダーク','settings.light':'☀️ ライト','settings.language':'言語',
    'settings.language_label':'アプリの言語',
    'settings.business':'マイビジネス','settings.businessName':'ビジネス名',
    'settings.saveName':'名前を保存','settings.saving':'保存中...',
    'settings.changePass':'パスワード変更','settings.currentPass':'現在のパスワード',
    'settings.newPass':'新しいパスワード','settings.confirmPass':'新しいパスワードを確認',
    'settings.changePassBtn':'パスワードを変更',
    'settings.changeEmail':'メールアドレス変更','settings.currentEmail':'現在のメール',
    'settings.newEmail':'新しいメール','settings.changeEmailBtn':'メールを変更',
    'settings.aiApi':'AI分析 — APIキー',
    'settings.privacy':'プライバシー','settings.telemetry':'匿名使用データ',
    'settings.telOn':'有効','settings.telOff':'無効',
    'settings.data':'データ','settings.exportToday':'本日の売上をエクスポート','settings.downloadCsv':'⬇ CSVをダウンロード',
    'sales.search':'製品を検索...','sales.cart':'カート','sales.total':'合計',
    'sales.checkout':'販売確認','sales.empty':'製品を選択','sales.registered':'注文 #',
    'history.title':'本日の履歴','history.total':'総売上','history.orders':'注文',
    'history.order':'注文','history.products':'製品',
    'board.title':'注文ボード','board.empty':'保留中の注文なし',
    'board.markDone':'完了としてマーク','board.done':'✓ 完了',
    'board.order':'注文 #',
    'calendar.title':'カレンダー','calendar.pickDay':'データを表示する日を選択',
    'calendar.totalSold':'総売上','calendar.orders':'注文','calendar.noSales':'この日の売上なし',
    'calendar.notes':'メモ','calendar.notesPlaceholder':'この日について何か書いてください...',
    'calendar.aiAnalysis':'その日のAI分析','calendar.analyzeBtn':'AIで分析',
    'calendar.analyzing':'分析中...','calendar.today':'今日',
    'calendar.daysWithSales':'売上のある日数',
    'ai.title':'AI分析','ai.today':'今日','ai.incomeToday':'今日の収入',
    'ai.salesToday':'今日の売上','ai.bestDay':'最高の日','ai.topProduct':'トップ製品',
    'ai.topProducts':'最も売れた製品',
    'common.save':'保存','common.cancel':'キャンセル','common.delete':'削除',
    'common.loading':'読み込み中...','common.error':'エラー','common.ok':'OK',
    'common.show':'表示','common.hide':'非表示',
    'consent.title':'Your Businessの改善にご協力ください',
    'consent.desc':'アプリを改善するために匿名の使用データを収集します。',
    'consent.accept':'承諾','consent.reject':'いいえ、結構です',
  },
  ar: {
    'nav.sales':'المبيعات','nav.products':'المنتجات','nav.history':'السجل',
    'nav.board':'اللوحة','nav.ai':'تحليل ذكاء اصطناعي','nav.calendar':'التقويم','nav.settings':'الإعدادات',
    'app.yourbiz':'نشاطي التجاري','app.logout':'تسجيل الخروج','app.version':'Your Business v1.2.1',
    'settings.title':'الإعدادات','settings.appearance':'المظهر','settings.theme':'سمة الواجهة',
    'settings.dark':'🌙 داكن','settings.light':'☀️ فاتح','settings.language':'اللغة',
    'settings.language_label':'لغة التطبيق',
    'settings.business':'نشاطي التجاري','settings.businessName':'اسم النشاط التجاري',
    'settings.saveName':'حفظ الاسم','settings.saving':'جاري الحفظ...',
    'settings.changePass':'تغيير كلمة المرور','settings.currentPass':'كلمة المرور الحالية',
    'settings.newPass':'كلمة المرور الجديدة','settings.confirmPass':'تأكيد الجديدة',
    'settings.changePassBtn':'تغيير كلمة المرور',
    'settings.changeEmail':'تغيير البريد الإلكتروني','settings.currentEmail':'البريد الحالي',
    'settings.newEmail':'البريد الجديد','settings.changeEmailBtn':'تغيير البريد',
    'settings.aiApi':'تحليل ذكاء اصطناعي — مفتاح API',
    'settings.privacy':'الخصوصية','settings.telemetry':'بيانات الاستخدام المجهولة',
    'settings.telOn':'مفعل','settings.telOff':'معطل',
    'settings.data':'البيانات','settings.exportToday':'تصدير مبيعات اليوم','settings.downloadCsv':'⬇ تنزيل CSV',
    'sales.search':'البحث عن منتج...','sales.cart':'السلة','sales.total':'المجموع',
    'sales.checkout':'تأكيد البيع','sales.empty':'اختر المنتجات','sales.registered':'طلب #',
    'history.title':'سجل اليوم','history.total':'إجمالي المبيعات','history.orders':'الطلبات',
    'history.order':'طلب','history.products':'المنتجات',
    'board.title':'لوحة الطلبات','board.empty':'لا توجد طلبات معلقة',
    'board.markDone':'وضع علامة كمنجز','board.done':'✓ منجز',
    'board.order':'طلب #',
    'calendar.title':'التقويم','calendar.pickDay':'اختر يوماً لعرض بياناته',
    'calendar.totalSold':'إجمالي المبيعات','calendar.orders':'الطلبات','calendar.noSales':'لا مبيعات هذا اليوم',
    'calendar.notes':'ملاحظات','calendar.notesPlaceholder':'اكتب شيئاً عن هذا اليوم...',
    'calendar.aiAnalysis':'تحليل ذكاء اصطناعي لليوم','calendar.analyzeBtn':'تحليل بالذكاء الاصطناعي',
    'calendar.analyzing':'جاري التحليل...','calendar.today':'اليوم',
    'calendar.daysWithSales':'أيام بمبيعات',
    'ai.title':'تحليل ذكاء اصطناعي','ai.today':'اليوم','ai.incomeToday':'إيرادات اليوم',
    'ai.salesToday':'مبيعات اليوم','ai.bestDay':'أفضل يوم','ai.topProduct':'المنتج الأفضل',
    'ai.topProducts':'أكثر المنتجات مبيعاً',
    'common.save':'حفظ','common.cancel':'إلغاء','common.delete':'حذف',
    'common.loading':'جاري التحميل...','common.error':'خطأ','common.ok':'موافق',
    'common.show':'إظهار','common.hide':'إخفاء',
    'consent.title':'ساعدنا في تحسين Your Business',
    'consent.desc':'نجمع بيانات استخدام مجهولة لتحسين التطبيق.',
    'consent.accept':'قبول','consent.reject':'لا، شكراً',
  },
  ko: {
    'nav.sales':'판매','nav.products':'제품','nav.history':'내역',
    'nav.board':'보드','nav.ai':'AI 분석','nav.calendar':'캘린더','nav.settings':'설정',
    'app.yourbiz':'내 사업','app.logout':'로그아웃','app.version':'Your Business v1.2.1',
    'settings.title':'설정','settings.appearance':'외관','settings.theme':'인터페이스 테마',
    'settings.dark':'🌙 다크','settings.light':'☀️ 라이트','settings.language':'언어',
    'settings.language_label':'앱 언어',
    'settings.business':'내 사업','settings.businessName':'사업체명',
    'settings.saveName':'이름 저장','settings.saving':'저장 중...',
    'settings.changePass':'비밀번호 변경','settings.currentPass':'현재 비밀번호',
    'settings.newPass':'새 비밀번호','settings.confirmPass':'새 비밀번호 확인',
    'settings.changePassBtn':'비밀번호 변경',
    'settings.changeEmail':'이메일 변경','settings.currentEmail':'현재 이메일',
    'settings.newEmail':'새 이메일','settings.changeEmailBtn':'이메일 변경',
    'settings.aiApi':'AI 분석 — API 키',
    'settings.privacy':'개인정보','settings.telemetry':'익명 사용 데이터',
    'settings.telOn':'활성화','settings.telOff':'비활성화',
    'settings.data':'데이터','settings.exportToday':'오늘 판매 내보내기','settings.downloadCsv':'⬇ CSV 다운로드',
    'sales.search':'제품 검색...','sales.cart':'장바구니','sales.total':'합계',
    'sales.checkout':'판매 확인','sales.empty':'제품을 선택하세요','sales.registered':'주문 #',
    'history.title':'오늘의 내역','history.total':'총 판매액','history.orders':'주문',
    'history.order':'주문','history.products':'제품',
    'board.title':'주문 보드','board.empty':'대기 중인 주문 없음',
    'board.markDone':'완료로 표시','board.done':'✓ 완료',
    'board.order':'주문 #',
    'calendar.title':'캘린더','calendar.pickDay':'데이터를 볼 날짜 선택',
    'calendar.totalSold':'총 판매액','calendar.orders':'주문','calendar.noSales':'이 날 판매 없음',
    'calendar.notes':'메모','calendar.notesPlaceholder':'이 날에 대해 메모하세요...',
    'calendar.aiAnalysis':'당일 AI 분석','calendar.analyzeBtn':'AI로 분석',
    'calendar.analyzing':'분석 중...','calendar.today':'오늘',
    'calendar.daysWithSales':'판매 있는 날',
    'ai.title':'AI 분석','ai.today':'오늘','ai.incomeToday':'오늘 수입',
    'ai.salesToday':'오늘 판매','ai.bestDay':'최고의 날','ai.topProduct':'베스트 제품',
    'ai.topProducts':'가장 많이 팔린 제품',
    'common.save':'저장','common.cancel':'취소','common.delete':'삭제',
    'common.loading':'로딩 중...','common.error':'오류','common.ok':'확인',
    'common.show':'보기','common.hide':'숨기기',
    'consent.title':'Your Business 개선에 도움을 주세요',
    'consent.desc':'앱 개선을 위해 익명 사용 데이터를 수집합니다.',
    'consent.accept':'수락','consent.reject':'아니요, 괜찮습니다',
  },
  ru: {
    'nav.sales':'Продажи','nav.products':'Продукты','nav.history':'История',
    'nav.board':'Доска','nav.ai':'ИИ-анализ','nav.calendar':'Календарь','nav.settings':'Настройки',
    'app.yourbiz':'Мой бизнес','app.logout':'Выйти','app.version':'Your Business v1.2.1',
    'settings.title':'Настройки','settings.appearance':'Внешний вид','settings.theme':'Тема интерфейса',
    'settings.dark':'🌙 Тёмная','settings.light':'☀️ Светлая','settings.language':'Язык',
    'settings.language_label':'Язык приложения',
    'settings.business':'Мой бизнес','settings.businessName':'Название бизнеса',
    'settings.saveName':'Сохранить','settings.saving':'Сохранение...',
    'settings.changePass':'Изменить пароль','settings.currentPass':'Текущий пароль',
    'settings.newPass':'Новый пароль','settings.confirmPass':'Подтвердить новый',
    'settings.changePassBtn':'Изменить пароль',
    'settings.changeEmail':'Изменить email','settings.currentEmail':'Текущий email',
    'settings.newEmail':'Новый email','settings.changeEmailBtn':'Изменить email',
    'settings.aiApi':'ИИ-анализ — API-ключ',
    'settings.privacy':'Конфиденциальность','settings.telemetry':'Анонимные данные об использовании',
    'settings.telOn':'Включено','settings.telOff':'Выключено',
    'settings.data':'Данные','settings.exportToday':'Экспорт продаж за сегодня','settings.downloadCsv':'⬇ Скачать CSV',
    'sales.search':'Поиск продукта...','sales.cart':'Корзина','sales.total':'Итого',
    'sales.checkout':'Подтвердить продажу','sales.empty':'Выберите продукты','sales.registered':'Заказ #',
    'history.title':'История дня','history.total':'Общая выручка','history.orders':'Заказы',
    'history.order':'Заказ','history.products':'Продукты',
    'board.title':'Доска заказов','board.empty':'Нет ожидающих заказов',
    'board.markDone':'Отметить как выполнено','board.done':'✓ Готово',
    'board.order':'Заказ #',
    'calendar.title':'Календарь','calendar.pickDay':'Выберите день для просмотра данных',
    'calendar.totalSold':'Общая выручка','calendar.orders':'Заказы','calendar.noSales':'Продаж в этот день нет',
    'calendar.notes':'Заметки','calendar.notesPlaceholder':'Запишите что-нибудь об этом дне...',
    'calendar.aiAnalysis':'ИИ-анализ дня','calendar.analyzeBtn':'Анализ с ИИ',
    'calendar.analyzing':'Анализ...','calendar.today':'Сегодня',
    'calendar.daysWithSales':'Дни с продажами',
    'ai.title':'ИИ-анализ','ai.today':'сегодня','ai.incomeToday':'выручка сегодня',
    'ai.salesToday':'Продажи сегодня','ai.bestDay':'Лучший день','ai.topProduct':'Топ продукт',
    'ai.topProducts':'Самые продаваемые продукты',
    'common.save':'Сохранить','common.cancel':'Отмена','common.delete':'Удалить',
    'common.loading':'Загрузка...','common.error':'Ошибка','common.ok':'ОК',
    'common.show':'Показать','common.hide':'Скрыть',
    'consent.title':'Помогите нам улучшить Your Business',
    'consent.desc':'Мы собираем анонимные данные об использовании для улучшения приложения.',
    'consent.accept':'Принять','consent.reject':'Нет, спасибо',
  },
  nl: {
    'nav.sales':'Verkoop','nav.products':'Producten','nav.history':'Geschiedenis',
    'nav.board':'Bord','nav.ai':'AI-analyse','nav.calendar':'Kalender','nav.settings':'Instellingen',
    'app.yourbiz':'Mijn bedrijf','app.logout':'Uitloggen','app.version':'Your Business v1.2.1',
    'settings.title':'Instellingen','settings.appearance':'Uiterlijk','settings.theme':'Interface thema',
    'settings.dark':'🌙 Donker','settings.light':'☀️ Licht','settings.language':'Taal',
    'settings.language_label':'App-taal',
    'settings.business':'Mijn bedrijf','settings.businessName':'Bedrijfsnaam',
    'settings.saveName':'Naam opslaan','settings.saving':'Opslaan...',
    'settings.changePass':'Wachtwoord wijzigen','settings.currentPass':'Huidig wachtwoord',
    'settings.newPass':'Nieuw wachtwoord','settings.confirmPass':'Bevestig nieuw',
    'settings.changePassBtn':'Wachtwoord wijzigen',
    'settings.changeEmail':'E-mail wijzigen','settings.currentEmail':'Huidig e-mail',
    'settings.newEmail':'Nieuw e-mail','settings.changeEmailBtn':'E-mail wijzigen',
    'settings.aiApi':'AI-analyse — API-sleutel',
    'settings.privacy':'Privacy','settings.telemetry':'Anonieme gebruiksgegevens',
    'settings.telOn':'Ingeschakeld','settings.telOff':'Uitgeschakeld',
    'settings.data':'Gegevens','settings.exportToday':'Verkopen van vandaag exporteren','settings.downloadCsv':'⬇ CSV downloaden',
    'sales.search':'Product zoeken...','sales.cart':'Winkelwagen','sales.total':'Totaal',
    'sales.checkout':'Verkoop bevestigen','sales.empty':'Producten selecteren','sales.registered':'Bestelling #',
    'history.title':'Geschiedenis van vandaag','history.total':'Totaal verkocht','history.orders':'Bestellingen',
    'history.order':'Bestelling','history.products':'Producten',
    'board.title':'Bestelbord','board.empty':'Geen openstaande bestellingen',
    'board.markDone':'Markeren als klaar','board.done':'✓ Klaar',
    'board.order':'Bestelling #',
    'calendar.title':'Kalender','calendar.pickDay':'Selecteer een dag om gegevens te bekijken',
    'calendar.totalSold':'Totaal verkocht','calendar.orders':'Bestellingen','calendar.noSales':'Geen verkopen deze dag',
    'calendar.notes':'Notities','calendar.notesPlaceholder':'Schrijf iets over deze dag...',
    'calendar.aiAnalysis':'AI-analyse van de dag','calendar.analyzeBtn':'Analyseren met AI',
    'calendar.analyzing':'Analyseren...','calendar.today':'Vandaag',
    'calendar.daysWithSales':'Dagen met verkopen',
    'ai.title':'AI-analyse','ai.today':'vandaag','ai.incomeToday':'inkomsten vandaag',
    'ai.salesToday':'Verkopen vandaag','ai.bestDay':'Beste dag','ai.topProduct':'Top product',
    'ai.topProducts':'Bestverkopende producten',
    'common.save':'Opslaan','common.cancel':'Annuleren','common.delete':'Verwijderen',
    'common.loading':'Laden...','common.error':'Fout','common.ok':'OK',
    'common.show':'Tonen','common.hide':'Verbergen',
    'consent.title':'Help ons Your Business te verbeteren',
    'consent.desc':'We verzamelen anonieme gebruiksgegevens om de app te verbeteren.',
    'consent.accept':'Accepteren','consent.reject':'Nee, bedankt',
  },
  pl: {
    'nav.sales':'Sprzedaż','nav.products':'Produkty','nav.history':'Historia',
    'nav.board':'Tablica','nav.ai':'Analiza AI','nav.calendar':'Kalendarz','nav.settings':'Ustawienia',
    'app.yourbiz':'Mój biznes','app.logout':'Wyloguj','app.version':'Your Business v1.2.1',
    'settings.title':'Ustawienia','settings.appearance':'Wygląd','settings.theme':'Motyw interfejsu',
    'settings.dark':'🌙 Ciemny','settings.light':'☀️ Jasny','settings.language':'Język',
    'settings.language_label':'Język aplikacji',
    'settings.business':'Mój biznes','settings.businessName':'Nazwa firmy',
    'settings.saveName':'Zapisz nazwę','settings.saving':'Zapisywanie...',
    'settings.changePass':'Zmień hasło','settings.currentPass':'Aktualne hasło',
    'settings.newPass':'Nowe hasło','settings.confirmPass':'Potwierdź nowe',
    'settings.changePassBtn':'Zmień hasło',
    'settings.changeEmail':'Zmień email','settings.currentEmail':'Aktualny email',
    'settings.newEmail':'Nowy email','settings.changeEmailBtn':'Zmień email',
    'settings.aiApi':'Analiza AI — Klucz API',
    'settings.privacy':'Prywatność','settings.telemetry':'Anonimowe dane użytkowania',
    'settings.telOn':'Włączone','settings.telOff':'Wyłączone',
    'settings.data':'Dane','settings.exportToday':'Eksportuj dzisiejszą sprzedaż','settings.downloadCsv':'⬇ Pobierz CSV',
    'sales.search':'Szukaj produktu...','sales.cart':'Koszyk','sales.total':'Suma',
    'sales.checkout':'Potwierdź sprzedaż','sales.empty':'Wybierz produkty','sales.registered':'Zamówienie #',
    'history.title':'Historia dnia','history.total':'Łączna sprzedaż','history.orders':'Zamówienia',
    'history.order':'Zamówienie','history.products':'Produkty',
    'board.title':'Tablica zamówień','board.empty':'Brak oczekujących zamówień',
    'board.markDone':'Oznacz jako gotowe','board.done':'✓ Gotowe',
    'board.order':'Zamówienie #',
    'calendar.title':'Kalendarz','calendar.pickDay':'Wybierz dzień, aby zobaczyć dane',
    'calendar.totalSold':'Łączna sprzedaż','calendar.orders':'Zamówienia','calendar.noSales':'Brak sprzedaży tego dnia',
    'calendar.notes':'Notatki','calendar.notesPlaceholder':'Zapisz coś o tym dniu...',
    'calendar.aiAnalysis':'Analiza AI dnia','calendar.analyzeBtn':'Analizuj z AI',
    'calendar.analyzing':'Analizowanie...','calendar.today':'Dziś',
    'calendar.daysWithSales':'Dni ze sprzedażą',
    'ai.title':'Analiza AI','ai.today':'dziś','ai.incomeToday':'przychody dziś',
    'ai.salesToday':'Sprzedaż dziś','ai.bestDay':'Najlepszy dzień','ai.topProduct':'Top produkt',
    'ai.topProducts':'Najlepiej sprzedające się produkty',
    'common.save':'Zapisz','common.cancel':'Anuluj','common.delete':'Usuń',
    'common.loading':'Ładowanie...','common.error':'Błąd','common.ok':'OK',
    'common.show':'Pokaż','common.hide':'Ukryj',
    'consent.title':'Pomóż nam ulepszyć Your Business',
    'consent.desc':'Zbieramy anonimowe dane użytkowania w celu ulepszenia aplikacji.',
    'consent.accept':'Akceptuj','consent.reject':'Nie, dziękuję',
  },
  tr: {
    'nav.sales':'Satışlar','nav.products':'Ürünler','nav.history':'Geçmiş',
    'nav.board':'Tahta','nav.ai':'YZ Analizi','nav.calendar':'Takvim','nav.settings':'Ayarlar',
    'app.yourbiz':'İşletmem','app.logout':'Çıkış yap','app.version':'Your Business v1.2.1',
    'settings.title':'Ayarlar','settings.appearance':'Görünüm','settings.theme':'Arayüz teması',
    'settings.dark':'🌙 Koyu','settings.light':'☀️ Açık','settings.language':'Dil',
    'settings.language_label':'Uygulama dili',
    'settings.business':'İşletmem','settings.businessName':'İşletme adı',
    'settings.saveName':'Adı kaydet','settings.saving':'Kaydediliyor...',
    'settings.changePass':'Şifre değiştir','settings.currentPass':'Mevcut şifre',
    'settings.newPass':'Yeni şifre','settings.confirmPass':'Yeni şifreyi onayla',
    'settings.changePassBtn':'Şifre değiştir',
    'settings.changeEmail':'E-posta değiştir','settings.currentEmail':'Mevcut e-posta',
    'settings.newEmail':'Yeni e-posta','settings.changeEmailBtn':'E-posta değiştir',
    'settings.aiApi':'YZ Analizi — API Anahtarı',
    'settings.privacy':'Gizlilik','settings.telemetry':'Anonim kullanım verileri',
    'settings.telOn':'Etkin','settings.telOff':'Devre dışı',
    'settings.data':'Veriler','settings.exportToday':'Bugünün satışlarını dışa aktar','settings.downloadCsv':'⬇ CSV indir',
    'sales.search':'Ürün ara...','sales.cart':'Sepet','sales.total':'Toplam',
    'sales.checkout':'Satışı onayla','sales.empty':'Ürün seçin','sales.registered':'Sipariş #',
    'history.title':'Günün geçmişi','history.total':'Toplam satış','history.orders':'Siparişler',
    'history.order':'Sipariş','history.products':'Ürünler',
    'board.title':'Sipariş tahtası','board.empty':'Bekleyen sipariş yok',
    'board.markDone':'Tamamlandı olarak işaretle','board.done':'✓ Tamam',
    'board.order':'Sipariş #',
    'calendar.title':'Takvim','calendar.pickDay':'Verileri görmek için bir gün seçin',
    'calendar.totalSold':'Toplam satış','calendar.orders':'Siparişler','calendar.noSales':'Bu gün satış yok',
    'calendar.notes':'Notlar','calendar.notesPlaceholder':'Bu gün hakkında bir şeyler yazın...',
    'calendar.aiAnalysis':'Günün YZ analizi','calendar.analyzeBtn':'YZ ile analiz et',
    'calendar.analyzing':'Analiz ediliyor...','calendar.today':'Bugün',
    'calendar.daysWithSales':'Satışlı günler',
    'ai.title':'YZ Analizi','ai.today':'bugün','ai.incomeToday':'bugünkü gelir',
    'ai.salesToday':'Bugünkü satışlar','ai.bestDay':'En iyi gün','ai.topProduct':'En iyi ürün',
    'ai.topProducts':'En çok satan ürünler',
    'common.save':'Kaydet','common.cancel':'İptal','common.delete':'Sil',
    'common.loading':'Yükleniyor...','common.error':'Hata','common.ok':'Tamam',
    'common.show':'Göster','common.hide':'Gizle',
    'consent.title':'Your Business\'i geliştirmemize yardım edin',
    'consent.desc':'Uygulamayı geliştirmek için anonim kullanım verileri topluyoruz.',
    'consent.accept':'Kabul et','consent.reject':'Hayır, teşekkürler',
  },
  hi: {
    'nav.sales':'बिक्री','nav.products':'उत्पाद','nav.history':'इतिहास',
    'nav.board':'बोर्ड','nav.ai':'AI विश्लेषण','nav.calendar':'कैलेंडर','nav.settings':'सेटिंग्स',
    'app.yourbiz':'मेरा व्यवसाय','app.logout':'लॉग आउट','app.version':'Your Business v1.2.1',
    'settings.title':'सेटिंग्स','settings.appearance':'दिखावट','settings.theme':'इंटरफ़ेस थीम',
    'settings.dark':'🌙 डार्क','settings.light':'☀️ लाइट','settings.language':'भाषा',
    'settings.language_label':'ऐप भाषा',
    'settings.business':'मेरा व्यवसाय','settings.businessName':'व्यवसाय का नाम',
    'settings.saveName':'नाम सहेजें','settings.saving':'सहेज रहे हैं...',
    'settings.changePass':'पासवर्ड बदलें','settings.currentPass':'वर्तमान पासवर्ड',
    'settings.newPass':'नया पासवर्ड','settings.confirmPass':'नए की पुष्टि करें',
    'settings.changePassBtn':'पासवर्ड बदलें',
    'settings.changeEmail':'ईमेल बदलें','settings.currentEmail':'वर्तमान ईमेल',
    'settings.newEmail':'नया ईमेल','settings.changeEmailBtn':'ईमेल बदलें',
    'settings.aiApi':'AI विश्लेषण — API कुंजी',
    'settings.privacy':'गोपनीयता','settings.telemetry':'अनाम उपयोग डेटा',
    'settings.telOn':'सक्षम','settings.telOff':'अक्षम',
    'settings.data':'डेटा','settings.exportToday':'आज की बिक्री निर्यात करें','settings.downloadCsv':'⬇ CSV डाउनलोड',
    'sales.search':'उत्पाद खोजें...','sales.cart':'कार्ट','sales.total':'कुल',
    'sales.checkout':'बिक्री की पुष्टि करें','sales.empty':'उत्पाद चुनें','sales.registered':'ऑर्डर #',
    'history.title':'आज का इतिहास','history.total':'कुल बिक्री','history.orders':'ऑर्डर',
    'history.order':'ऑर्डर','history.products':'उत्पाद',
    'board.title':'ऑर्डर बोर्ड','board.empty':'कोई लंबित ऑर्डर नहीं',
    'board.markDone':'पूर्ण के रूप में चिह्नित करें','board.done':'✓ हो गया',
    'board.order':'ऑर्डर #',
    'calendar.title':'कैलेंडर','calendar.pickDay':'डेटा देखने के लिए एक दिन चुनें',
    'calendar.totalSold':'कुल बिक्री','calendar.orders':'ऑर्डर','calendar.noSales':'इस दिन कोई बिक्री नहीं',
    'calendar.notes':'नोट्स','calendar.notesPlaceholder':'इस दिन के बारे में कुछ लिखें...',
    'calendar.aiAnalysis':'दिन का AI विश्लेषण','calendar.analyzeBtn':'AI से विश्लेषण करें',
    'calendar.analyzing':'विश्लेषण हो रहा है...','calendar.today':'आज',
    'calendar.daysWithSales':'बिक्री वाले दिन',
    'ai.title':'AI विश्लेषण','ai.today':'आज','ai.incomeToday':'आज की आय',
    'ai.salesToday':'आज की बिक्री','ai.bestDay':'सबसे अच्छा दिन','ai.topProduct':'टॉप उत्पाद',
    'ai.topProducts':'सबसे ज़्यादा बिकने वाले उत्पाद',
    'common.save':'सहेजें','common.cancel':'रद्द करें','common.delete':'हटाएं',
    'common.loading':'लोड हो रहा है...','common.error':'त्रुटि','common.ok':'ठीक है',
    'common.show':'दिखाएं','common.hide':'छुपाएं',
    'consent.title':'Your Business को बेहतर बनाने में मदद करें',
    'consent.desc':'ऐप को बेहतर बनाने के लिए हम अनाम उपयोग डेटा एकत्र करते हैं।',
    'consent.accept':'स्वीकार करें','consent.reject':'नहीं, धन्यवाद',
  },
  sv: {
    'nav.sales':'Försäljning','nav.products':'Produkter','nav.history':'Historik',
    'nav.board':'Tavla','nav.ai':'AI-analys','nav.calendar':'Kalender','nav.settings':'Inställningar',
    'app.yourbiz':'Mitt företag','app.logout':'Logga ut','app.version':'Your Business v1.2.1',
    'settings.title':'Inställningar','settings.appearance':'Utseende','settings.theme':'Gränssnittstema',
    'settings.dark':'🌙 Mörk','settings.light':'☀️ Ljus','settings.language':'Språk',
    'settings.language_label':'Appens språk',
    'settings.business':'Mitt företag','settings.businessName':'Företagsnamn',
    'settings.saveName':'Spara namn','settings.saving':'Sparar...',
    'settings.changePass':'Ändra lösenord','settings.currentPass':'Nuvarande lösenord',
    'settings.newPass':'Nytt lösenord','settings.confirmPass':'Bekräfta nytt',
    'settings.changePassBtn':'Ändra lösenord',
    'settings.changeEmail':'Ändra e-post','settings.currentEmail':'Nuvarande e-post',
    'settings.newEmail':'Ny e-post','settings.changeEmailBtn':'Ändra e-post',
    'settings.aiApi':'AI-analys — API-nyckel',
    'settings.privacy':'Integritet','settings.telemetry':'Anonym användningsdata',
    'settings.telOn':'Aktiverad','settings.telOff':'Inaktiverad',
    'settings.data':'Data','settings.exportToday':'Exportera dagens försäljning','settings.downloadCsv':'⬇ Ladda ner CSV',
    'sales.search':'Sök produkt...','sales.cart':'Varukorg','sales.total':'Totalt',
    'sales.checkout':'Bekräfta försäljning','sales.empty':'Välj produkter','sales.registered':'Order #',
    'history.title':'Dagens historik','history.total':'Totalt sålt','history.orders':'Beställningar',
    'history.order':'Beställning','history.products':'Produkter',
    'board.title':'Beställningstavla','board.empty':'Inga väntande beställningar',
    'board.markDone':'Markera som klar','board.done':'✓ Klar',
    'board.order':'Beställning #',
    'calendar.title':'Kalender','calendar.pickDay':'Välj en dag för att se data',
    'calendar.totalSold':'Totalt sålt','calendar.orders':'Beställningar','calendar.noSales':'Inga försäljningar denna dag',
    'calendar.notes':'Anteckningar','calendar.notesPlaceholder':'Skriv något om den här dagen...',
    'calendar.aiAnalysis':'Dagens AI-analys','calendar.analyzeBtn':'Analysera med AI',
    'calendar.analyzing':'Analyserar...','calendar.today':'Idag',
    'calendar.daysWithSales':'Dagar med försäljning',
    'ai.title':'AI-analys','ai.today':'idag','ai.incomeToday':'intäkter idag',
    'ai.salesToday':'Försäljning idag','ai.bestDay':'Bästa dag','ai.topProduct':'Toppprodukt',
    'ai.topProducts':'Mest sålda produkter',
    'common.save':'Spara','common.cancel':'Avbryt','common.delete':'Ta bort',
    'common.loading':'Laddar...','common.error':'Fel','common.ok':'OK',
    'common.show':'Visa','common.hide':'Dölj',
    'consent.title':'Hjälp oss förbättra Your Business',
    'consent.desc':'Vi samlar in anonym användningsdata för att förbättra appen.',
    'consent.accept':'Acceptera','consent.reject':'Nej tack',
  },
  no: {
    'nav.sales':'Salg','nav.products':'Produkter','nav.history':'Historikk',
    'nav.board':'Tavle','nav.ai':'AI-analyse','nav.calendar':'Kalender','nav.settings':'Innstillinger',
    'app.yourbiz':'Min bedrift','app.logout':'Logg ut','app.version':'Your Business v1.2.1',
    'settings.title':'Innstillinger','settings.appearance':'Utseende','settings.theme':'Grensesnittema',
    'settings.dark':'🌙 Mørk','settings.light':'☀️ Lys','settings.language':'Språk',
    'settings.language_label':'Appspråk',
    'settings.business':'Min bedrift','settings.businessName':'Bedriftsnavn',
    'settings.saveName':'Lagre navn','settings.saving':'Lagrer...',
    'settings.changePass':'Endre passord','settings.currentPass':'Nåværende passord',
    'settings.newPass':'Nytt passord','settings.confirmPass':'Bekreft nytt',
    'settings.changePassBtn':'Endre passord',
    'settings.changeEmail':'Endre e-post','settings.currentEmail':'Nåværende e-post',
    'settings.newEmail':'Ny e-post','settings.changeEmailBtn':'Endre e-post',
    'settings.aiApi':'AI-analyse — API-nøkkel',
    'settings.privacy':'Personvern','settings.telemetry':'Anonym bruksdata',
    'settings.telOn':'Aktivert','settings.telOff':'Deaktivert',
    'settings.data':'Data','settings.exportToday':'Eksporter dagens salg','settings.downloadCsv':'⬇ Last ned CSV',
    'sales.search':'Søk etter produkt...','sales.cart':'Handlekurv','sales.total':'Totalt',
    'sales.checkout':'Bekreft salg','sales.empty':'Velg produkter','sales.registered':'Bestilling #',
    'history.title':'Dagens historikk','history.total':'Totalt solgt','history.orders':'Bestillinger',
    'history.order':'Bestilling','history.products':'Produkter',
    'board.title':'Bestillingstavle','board.empty':'Ingen ventende bestillinger',
    'board.markDone':'Merk som ferdig','board.done':'✓ Ferdig',
    'board.order':'Bestilling #',
    'calendar.title':'Kalender','calendar.pickDay':'Velg en dag for å se data',
    'calendar.totalSold':'Totalt solgt','calendar.orders':'Bestillinger','calendar.noSales':'Ingen salg denne dagen',
    'calendar.notes':'Notater','calendar.notesPlaceholder':'Skriv noe om denne dagen...',
    'calendar.aiAnalysis':'Dagens AI-analyse','calendar.analyzeBtn':'Analyser med AI',
    'calendar.analyzing':'Analyserer...','calendar.today':'I dag',
    'calendar.daysWithSales':'Dager med salg',
    'ai.title':'AI-analyse','ai.today':'i dag','ai.incomeToday':'inntekter i dag',
    'ai.salesToday':'Salg i dag','ai.bestDay':'Beste dag','ai.topProduct':'Toppprodukt',
    'ai.topProducts':'Mest solgte produkter',
    'common.save':'Lagre','common.cancel':'Avbryt','common.delete':'Slett',
    'common.loading':'Laster...','common.error':'Feil','common.ok':'OK',
    'common.show':'Vis','common.hide':'Skjul',
    'consent.title':'Hjelp oss å forbedre Your Business',
    'consent.desc':'Vi samler inn anonym bruksdata for å forbedre appen.',
    'consent.accept':'Godta','consent.reject':'Nei takk',
  },
  da: {
    'nav.sales':'Salg','nav.products':'Produkter','nav.history':'Historik',
    'nav.board':'Tavle','nav.ai':'AI-analyse','nav.calendar':'Kalender','nav.settings':'Indstillinger',
    'app.yourbiz':'Min virksomhed','app.logout':'Log ud','app.version':'Your Business v1.2.1',
    'settings.title':'Indstillinger','settings.appearance':'Udseende','settings.theme':'Grænsefladetema',
    'settings.dark':'🌙 Mørk','settings.light':'☀️ Lys','settings.language':'Sprog',
    'settings.language_label':'App-sprog',
    'settings.business':'Min virksomhed','settings.businessName':'Virksomhedsnavn',
    'settings.saveName':'Gem navn','settings.saving':'Gemmer...',
    'settings.changePass':'Skift adgangskode','settings.currentPass':'Nuværende adgangskode',
    'settings.newPass':'Ny adgangskode','settings.confirmPass':'Bekræft ny',
    'settings.changePassBtn':'Skift adgangskode',
    'settings.changeEmail':'Skift e-mail','settings.currentEmail':'Nuværende e-mail',
    'settings.newEmail':'Ny e-mail','settings.changeEmailBtn':'Skift e-mail',
    'settings.aiApi':'AI-analyse — API-nøgle',
    'settings.privacy':'Privatliv','settings.telemetry':'Anonyme brugsdata',
    'settings.telOn':'Aktiveret','settings.telOff':'Deaktiveret',
    'settings.data':'Data','settings.exportToday':'Eksporter dagens salg','settings.downloadCsv':'⬇ Download CSV',
    'sales.search':'Søg produkt...','sales.cart':'Indkøbskurv','sales.total':'I alt',
    'sales.checkout':'Bekræft salg','sales.empty':'Vælg produkter','sales.registered':'Ordre #',
    'history.title':'Dagens historik','history.total':'Totalt solgt','history.orders':'Ordrer',
    'history.order':'Ordre','history.products':'Produkter',
    'board.title':'Ordretavle','board.empty':'Ingen afventende ordrer',
    'board.markDone':'Marker som færdig','board.done':'✓ Færdig',
    'board.order':'Ordre #',
    'calendar.title':'Kalender','calendar.pickDay':'Vælg en dag for at se data',
    'calendar.totalSold':'Totalt solgt','calendar.orders':'Ordrer','calendar.noSales':'Ingen salg denne dag',
    'calendar.notes':'Noter','calendar.notesPlaceholder':'Skriv noget om denne dag...',
    'calendar.aiAnalysis':'Dagens AI-analyse','calendar.analyzeBtn':'Analyser med AI',
    'calendar.analyzing':'Analyserer...','calendar.today':'I dag',
    'calendar.daysWithSales':'Dage med salg',
    'ai.title':'AI-analyse','ai.today':'i dag','ai.incomeToday':'indtægter i dag',
    'ai.salesToday':'Salg i dag','ai.bestDay':'Bedste dag','ai.topProduct':'Topprodukt',
    'ai.topProducts':'Mest solgte produkter',
    'common.save':'Gem','common.cancel':'Annuller','common.delete':'Slet',
    'common.loading':'Indlæser...','common.error':'Fejl','common.ok':'OK',
    'common.show':'Vis','common.hide':'Skjul',
    'consent.title':'Hjælp os med at forbedre Your Business',
    'consent.desc':'Vi indsamler anonyme brugsdata for at forbedre appen.',
    'consent.accept':'Accepter','consent.reject':'Nej tak',
  },
  fi: {
    'nav.sales':'Myynti','nav.products':'Tuotteet','nav.history':'Historia',
    'nav.board':'Taulu','nav.ai':'AI-analyysi','nav.calendar':'Kalenteri','nav.settings':'Asetukset',
    'app.yourbiz':'Yritykseni','app.logout':'Kirjaudu ulos','app.version':'Your Business v1.2.1',
    'settings.title':'Asetukset','settings.appearance':'Ulkoasu','settings.theme':'Käyttöliittymäteema',
    'settings.dark':'🌙 Tumma','settings.light':'☀️ Vaalea','settings.language':'Kieli',
    'settings.language_label':'Sovelluksen kieli',
    'settings.business':'Yritykseni','settings.businessName':'Yrityksen nimi',
    'settings.saveName':'Tallenna nimi','settings.saving':'Tallennetaan...',
    'settings.changePass':'Vaihda salasana','settings.currentPass':'Nykyinen salasana',
    'settings.newPass':'Uusi salasana','settings.confirmPass':'Vahvista uusi',
    'settings.changePassBtn':'Vaihda salasana',
    'settings.changeEmail':'Vaihda sähköposti','settings.currentEmail':'Nykyinen sähköposti',
    'settings.newEmail':'Uusi sähköposti','settings.changeEmailBtn':'Vaihda sähköposti',
    'settings.aiApi':'AI-analyysi — API-avain',
    'settings.privacy':'Yksityisyys','settings.telemetry':'Anonyymit käyttötiedot',
    'settings.telOn':'Käytössä','settings.telOff':'Ei käytössä',
    'settings.data':'Tiedot','settings.exportToday':'Vie tämän päivän myynti','settings.downloadCsv':'⬇ Lataa CSV',
    'sales.search':'Hae tuotetta...','sales.cart':'Ostoskori','sales.total':'Yhteensä',
    'sales.checkout':'Vahvista myynti','sales.empty':'Valitse tuotteet','sales.registered':'Tilaus #',
    'history.title':'Päivän historia','history.total':'Myyty yhteensä','history.orders':'Tilaukset',
    'history.order':'Tilaus','history.products':'Tuotteet',
    'board.title':'Tilaustaulukko','board.empty':'Ei odottavia tilauksia',
    'board.markDone':'Merkitse valmiiksi','board.done':'✓ Valmis',
    'board.order':'Tilaus #',
    'calendar.title':'Kalenteri','calendar.pickDay':'Valitse päivä nähdäksesi tiedot',
    'calendar.totalSold':'Myyty yhteensä','calendar.orders':'Tilaukset','calendar.noSales':'Ei myyntiä tänä päivänä',
    'calendar.notes':'Muistiinpanot','calendar.notesPlaceholder':'Kirjoita jotain tästä päivästä...',
    'calendar.aiAnalysis':'Päivän AI-analyysi','calendar.analyzeBtn':'Analysoi AI:lla',
    'calendar.analyzing':'Analysoidaan...','calendar.today':'Tänään',
    'calendar.daysWithSales':'Myyntipäiviä',
    'ai.title':'AI-analyysi','ai.today':'tänään','ai.incomeToday':'tulot tänään',
    'ai.salesToday':'Myynti tänään','ai.bestDay':'Paras päivä','ai.topProduct':'Huippuprodukt',
    'ai.topProducts':'Myydyimmät tuotteet',
    'common.save':'Tallenna','common.cancel':'Peruuta','common.delete':'Poista',
    'common.loading':'Ladataan...','common.error':'Virhe','common.ok':'OK',
    'common.show':'Näytä','common.hide':'Piilota',
    'consent.title':'Auta meitä parantamaan Your Businessia',
    'consent.desc':'Keräämme anonyymejä käyttötietoja sovelluksen parantamiseksi.',
    'consent.accept':'Hyväksy','consent.reject':'Ei kiitos',
  },
  el: {
    'nav.sales':'Πωλήσεις','nav.products':'Προϊόντα','nav.history':'Ιστορικό',
    'nav.board':'Πίνακας','nav.ai':'Ανάλυση ΑΙ','nav.calendar':'Ημερολόγιο','nav.settings':'Ρυθμίσεις',
    'app.yourbiz':'Η επιχείρησή μου','app.logout':'Αποσύνδεση','app.version':'Your Business v1.2.1',
    'settings.title':'Ρυθμίσεις','settings.appearance':'Εμφάνιση','settings.theme':'Θέμα διεπαφής',
    'settings.dark':'🌙 Σκοτεινό','settings.light':'☀️ Φωτεινό','settings.language':'Γλώσσα',
    'settings.language_label':'Γλώσσα εφαρμογής',
    'settings.business':'Η επιχείρησή μου','settings.businessName':'Όνομα επιχείρησης',
    'settings.saveName':'Αποθήκευση ονόματος','settings.saving':'Αποθήκευση...',
    'settings.changePass':'Αλλαγή κωδικού','settings.currentPass':'Τρέχων κωδικός',
    'settings.newPass':'Νέος κωδικός','settings.confirmPass':'Επιβεβαίωση νέου',
    'settings.changePassBtn':'Αλλαγή κωδικού',
    'settings.changeEmail':'Αλλαγή email','settings.currentEmail':'Τρέχον email',
    'settings.newEmail':'Νέο email','settings.changeEmailBtn':'Αλλαγή email',
    'settings.aiApi':'Ανάλυση ΑΙ — Κλειδί API',
    'settings.privacy':'Απόρρητο','settings.telemetry':'Ανώνυμα δεδομένα χρήσης',
    'settings.telOn':'Ενεργοποιημένο','settings.telOff':'Απενεργοποιημένο',
    'settings.data':'Δεδομένα','settings.exportToday':'Εξαγωγή σημερινών πωλήσεων','settings.downloadCsv':'⬇ Λήψη CSV',
    'sales.search':'Αναζήτηση προϊόντος...','sales.cart':'Καλάθι','sales.total':'Σύνολο',
    'sales.checkout':'Επιβεβαίωση πώλησης','sales.empty':'Επιλέξτε προϊόντα','sales.registered':'Παραγγελία #',
    'history.title':'Ιστορικό ημέρας','history.total':'Συνολικές πωλήσεις','history.orders':'Παραγγελίες',
    'history.order':'Παραγγελία','history.products':'Προϊόντα',
    'board.title':'Πίνακας παραγγελιών','board.empty':'Δεν υπάρχουν εκκρεμείς παραγγελίες',
    'board.markDone':'Σήμανση ως ολοκληρωμένο','board.done':'✓ Έτοιμο',
    'board.order':'Παραγγελία #',
    'calendar.title':'Ημερολόγιο','calendar.pickDay':'Επιλέξτε ημέρα για προβολή δεδομένων',
    'calendar.totalSold':'Συνολικές πωλήσεις','calendar.orders':'Παραγγελίες','calendar.noSales':'Χωρίς πωλήσεις αυτή την ημέρα',
    'calendar.notes':'Σημειώσεις','calendar.notesPlaceholder':'Γράψτε κάτι για αυτή την ημέρα...',
    'calendar.aiAnalysis':'Ανάλυση ΑΙ ημέρας','calendar.analyzeBtn':'Ανάλυση με ΑΙ',
    'calendar.analyzing':'Ανάλυση...','calendar.today':'Σήμερα',
    'calendar.daysWithSales':'Ημέρες με πωλήσεις',
    'ai.title':'Ανάλυση ΑΙ','ai.today':'σήμερα','ai.incomeToday':'έσοδα σήμερα',
    'ai.salesToday':'Πωλήσεις σήμερα','ai.bestDay':'Καλύτερη μέρα','ai.topProduct':'Κορυφαίο προϊόν',
    'ai.topProducts':'Πιο δημοφιλή προϊόντα',
    'common.save':'Αποθήκευση','common.cancel':'Ακύρωση','common.delete':'Διαγραφή',
    'common.loading':'Φόρτωση...','common.error':'Σφάλμα','common.ok':'ΟΚ',
    'common.show':'Εμφάνιση','common.hide':'Απόκρυψη',
    'consent.title':'Βοηθήστε μας να βελτιώσουμε το Your Business',
    'consent.desc':'Συλλέγουμε ανώνυμα δεδομένα χρήσης για να βελτιώσουμε την εφαρμογή.',
    'consent.accept':'Αποδοχή','consent.reject':'Όχι, ευχαριστώ',
  },
  he: {
    'nav.sales':'מכירות','nav.products':'מוצרים','nav.history':'היסטוריה',
    'nav.board':'לוח','nav.ai':'ניתוח AI','nav.calendar':'לוח שנה','nav.settings':'הגדרות',
    'app.yourbiz':'העסק שלי','app.logout':'התנתק','app.version':'Your Business v1.2.1',
    'settings.title':'הגדרות','settings.appearance':'מראה','settings.theme':'ערכת נושא ממשק',
    'settings.dark':'🌙 כהה','settings.light':'☀️ בהיר','settings.language':'שפה',
    'settings.language_label':'שפת האפליקציה',
    'settings.business':'העסק שלי','settings.businessName':'שם העסק',
    'settings.saveName':'שמור שם','settings.saving':'שומר...',
    'settings.changePass':'שנה סיסמה','settings.currentPass':'סיסמה נוכחית',
    'settings.newPass':'סיסמה חדשה','settings.confirmPass':'אשר חדשה',
    'settings.changePassBtn':'שנה סיסמה',
    'settings.changeEmail':'שנה דואר אלקטרוני','settings.currentEmail':'דואר נוכחי',
    'settings.newEmail':'דואר חדש','settings.changeEmailBtn':'שנה דואר',
    'settings.aiApi':'ניתוח AI — מפתח API',
    'settings.privacy':'פרטיות','settings.telemetry':'נתוני שימוש אנונימיים',
    'settings.telOn':'מופעל','settings.telOff':'מושבת',
    'settings.data':'נתונים','settings.exportToday':'ייצוא מכירות היום','settings.downloadCsv':'⬇ הורד CSV',
    'sales.search':'חיפוש מוצר...','sales.cart':'עגלה','sales.total':'סה"כ',
    'sales.checkout':'אשר מכירה','sales.empty':'בחר מוצרים','sales.registered':'הזמנה #',
    'history.title':'היסטוריית היום','history.total':'סה"כ שנמכר','history.orders':'הזמנות',
    'history.order':'הזמנה','history.products':'מוצרים',
    'board.title':'לוח הזמנות','board.empty':'אין הזמנות ממתינות',
    'board.markDone':'סמן כהושלם','board.done':'✓ הושלם',
    'board.order':'הזמנה #',
    'calendar.title':'לוח שנה','calendar.pickDay':'בחר יום לצפייה בנתונים',
    'calendar.totalSold':'סה"כ שנמכר','calendar.orders':'הזמנות','calendar.noSales':'אין מכירות ביום זה',
    'calendar.notes':'הערות','calendar.notesPlaceholder':'כתוב משהו על יום זה...',
    'calendar.aiAnalysis':'ניתוח AI ליום','calendar.analyzeBtn':'נתח עם AI',
    'calendar.analyzing':'מנתח...','calendar.today':'היום',
    'calendar.daysWithSales':'ימים עם מכירות',
    'ai.title':'ניתוח AI','ai.today':'היום','ai.incomeToday':'הכנסות היום',
    'ai.salesToday':'מכירות היום','ai.bestDay':'יום הכי טוב','ai.topProduct':'מוצר מוביל',
    'ai.topProducts':'המוצרים הנמכרים ביותר',
    'common.save':'שמור','common.cancel':'ביטול','common.delete':'מחק',
    'common.loading':'טוען...','common.error':'שגיאה','common.ok':'אישור',
    'common.show':'הצג','common.hide':'הסתר',
    'consent.title':'עזור לנו לשפר את Your Business',
    'consent.desc':'אנו אוספים נתוני שימוש אנונימיים לשיפור האפליקציה.',
    'consent.accept':'קבל','consent.reject':'לא, תודה',
  },
  ro: {
    'nav.sales':'Vânzări','nav.products':'Produse','nav.history':'Istoric',
    'nav.board':'Tablă','nav.ai':'Analiză IA','nav.calendar':'Calendar','nav.settings':'Setări',
    'app.yourbiz':'Afacerea mea','app.logout':'Deconectare','app.version':'Your Business v1.2.1',
    'settings.title':'Setări','settings.appearance':'Aspect','settings.theme':'Temă interfață',
    'settings.dark':'🌙 Întunecat','settings.light':'☀️ Deschis','settings.language':'Limbă',
    'settings.language_label':'Limba aplicației',
    'settings.business':'Afacerea mea','settings.businessName':'Numele afacerii',
    'settings.saveName':'Salvează numele','settings.saving':'Se salvează...',
    'settings.changePass':'Schimbă parola','settings.currentPass':'Parola actuală',
    'settings.newPass':'Parolă nouă','settings.confirmPass':'Confirmă noua',
    'settings.changePassBtn':'Schimbă parola',
    'settings.changeEmail':'Schimbă email','settings.currentEmail':'Email actual',
    'settings.newEmail':'Email nou','settings.changeEmailBtn':'Schimbă email',
    'settings.aiApi':'Analiză IA — Cheie API',
    'settings.privacy':'Confidențialitate','settings.telemetry':'Date de utilizare anonime',
    'settings.telOn':'Activat','settings.telOff':'Dezactivat',
    'settings.data':'Date','settings.exportToday':'Exportă vânzările de astăzi','settings.downloadCsv':'⬇ Descarcă CSV',
    'sales.search':'Caută produs...','sales.cart':'Coș','sales.total':'Total',
    'sales.checkout':'Confirmă vânzarea','sales.empty':'Selectează produse','sales.registered':'Comandă #',
    'history.title':'Istoricul zilei','history.total':'Total vândut','history.orders':'Comenzi',
    'history.order':'Comandă','history.products':'Produse',
    'board.title':'Tablă comenzi','board.empty':'Nicio comandă în așteptare',
    'board.markDone':'Marchează ca gata','board.done':'✓ Gata',
    'board.order':'Comandă #',
    'calendar.title':'Calendar','calendar.pickDay':'Selectează o zi pentru a vedea datele',
    'calendar.totalSold':'Total vândut','calendar.orders':'Comenzi','calendar.noSales':'Nicio vânzare în această zi',
    'calendar.notes':'Note','calendar.notesPlaceholder':'Scrie ceva despre această zi...',
    'calendar.aiAnalysis':'Analiză IA a zilei','calendar.analyzeBtn':'Analizează cu IA',
    'calendar.analyzing':'Analizând...','calendar.today':'Azi',
    'calendar.daysWithSales':'Zile cu vânzări',
    'ai.title':'Analiză IA','ai.today':'azi','ai.incomeToday':'venituri azi',
    'ai.salesToday':'Vânzări azi','ai.bestDay':'Cea mai bună zi','ai.topProduct':'Produs top',
    'ai.topProducts':'Cele mai vândute produse',
    'common.save':'Salvează','common.cancel':'Anulează','common.delete':'Șterge',
    'common.loading':'Se încarcă...','common.error':'Eroare','common.ok':'OK',
    'common.show':'Arată','common.hide':'Ascunde',
    'consent.title':'Ajută-ne să îmbunătățim Your Business',
    'consent.desc':'Colectăm date anonime de utilizare pentru a îmbunătăți aplicația.',
    'consent.accept':'Acceptă','consent.reject':'Nu, mulțumesc',
  },
  cs: {
    'nav.sales':'Prodej','nav.products':'Produkty','nav.history':'Historie',
    'nav.board':'Tabule','nav.ai':'AI analýza','nav.calendar':'Kalendář','nav.settings':'Nastavení',
    'app.yourbiz':'Můj podnik','app.logout':'Odhlásit se','app.version':'Your Business v1.2.1',
    'settings.title':'Nastavení','settings.appearance':'Vzhled','settings.theme':'Téma rozhraní',
    'settings.dark':'🌙 Tmavé','settings.light':'☀️ Světlé','settings.language':'Jazyk',
    'settings.language_label':'Jazyk aplikace',
    'settings.business':'Můj podnik','settings.businessName':'Název podniku',
    'settings.saveName':'Uložit název','settings.saving':'Ukládám...',
    'settings.changePass':'Změnit heslo','settings.currentPass':'Aktuální heslo',
    'settings.newPass':'Nové heslo','settings.confirmPass':'Potvrdit nové',
    'settings.changePassBtn':'Změnit heslo',
    'settings.changeEmail':'Změnit e-mail','settings.currentEmail':'Aktuální e-mail',
    'settings.newEmail':'Nový e-mail','settings.changeEmailBtn':'Změnit e-mail',
    'settings.aiApi':'AI analýza — Klíč API',
    'settings.privacy':'Soukromí','settings.telemetry':'Anonymní data o používání',
    'settings.telOn':'Povoleno','settings.telOff':'Zakázáno',
    'settings.data':'Data','settings.exportToday':'Exportovat dnešní prodeje','settings.downloadCsv':'⬇ Stáhnout CSV',
    'sales.search':'Hledat produkt...','sales.cart':'Košík','sales.total':'Celkem',
    'sales.checkout':'Potvrdit prodej','sales.empty':'Vyberte produkty','sales.registered':'Objednávka #',
    'history.title':'Historie dne','history.total':'Celkový prodej','history.orders':'Objednávky',
    'history.order':'Objednávka','history.products':'Produkty',
    'board.title':'Tabule objednávek','board.empty':'Žádné čekající objednávky',
    'board.markDone':'Označit jako hotové','board.done':'✓ Hotovo',
    'board.order':'Objednávka #',
    'calendar.title':'Kalendář','calendar.pickDay':'Vyberte den pro zobrazení dat',
    'calendar.totalSold':'Celkový prodej','calendar.orders':'Objednávky','calendar.noSales':'Žádný prodej tento den',
    'calendar.notes':'Poznámky','calendar.notesPlaceholder':'Napište něco o tomto dni...',
    'calendar.aiAnalysis':'AI analýza dne','calendar.analyzeBtn':'Analyzovat s AI',
    'calendar.analyzing':'Analyzuji...','calendar.today':'Dnes',
    'calendar.daysWithSales':'Dny s prodejem',
    'ai.title':'AI analýza','ai.today':'dnes','ai.incomeToday':'příjmy dnes',
    'ai.salesToday':'Prodeje dnes','ai.bestDay':'Nejlepší den','ai.topProduct':'Top produkt',
    'ai.topProducts':'Nejprodávanější produkty',
    'common.save':'Uložit','common.cancel':'Zrušit','common.delete':'Smazat',
    'common.loading':'Načítám...','common.error':'Chyba','common.ok':'OK',
    'common.show':'Zobrazit','common.hide':'Skrýt',
    'consent.title':'Pomozte nám vylepšit Your Business',
    'consent.desc':'Shromažďujeme anonymní data o používání pro zlepšení aplikace.',
    'consent.accept':'Přijmout','consent.reject':'Ne, děkuji',
  },
  hu: {
    'nav.sales':'Értékesítés','nav.products':'Termékek','nav.history':'Előzmények',
    'nav.board':'Tábla','nav.ai':'AI elemzés','nav.calendar':'Naptár','nav.settings':'Beállítások',
    'app.yourbiz':'Vállalkozásom','app.logout':'Kijelentkezés','app.version':'Your Business v1.2.1',
    'settings.title':'Beállítások','settings.appearance':'Megjelenés','settings.theme':'Felület téma',
    'settings.dark':'🌙 Sötét','settings.light':'☀️ Világos','settings.language':'Nyelv',
    'settings.language_label':'Alkalmazás nyelve',
    'settings.business':'Vállalkozásom','settings.businessName':'Vállalkozás neve',
    'settings.saveName':'Név mentése','settings.saving':'Mentés...',
    'settings.changePass':'Jelszó módosítása','settings.currentPass':'Jelenlegi jelszó',
    'settings.newPass':'Új jelszó','settings.confirmPass':'Új megerősítése',
    'settings.changePassBtn':'Jelszó módosítása',
    'settings.changeEmail':'E-mail módosítása','settings.currentEmail':'Jelenlegi e-mail',
    'settings.newEmail':'Új e-mail','settings.changeEmailBtn':'E-mail módosítása',
    'settings.aiApi':'AI elemzés — API kulcs',
    'settings.privacy':'Adatvédelem','settings.telemetry':'Anonim használati adatok',
    'settings.telOn':'Bekapcsolva','settings.telOff':'Kikapcsolva',
    'settings.data':'Adatok','settings.exportToday':'Mai eladások exportálása','settings.downloadCsv':'⬇ CSV letöltése',
    'sales.search':'Termék keresése...','sales.cart':'Kosár','sales.total':'Összesen',
    'sales.checkout':'Eladás megerősítése','sales.empty':'Válasszon termékeket','sales.registered':'Rendelés #',
    'history.title':'Napi előzmények','history.total':'Összesen eladva','history.orders':'Rendelések',
    'history.order':'Rendelés','history.products':'Termékek',
    'board.title':'Rendelési tábla','board.empty':'Nincsenek függőben lévő rendelések',
    'board.markDone':'Készként jelölés','board.done':'✓ Kész',
    'board.order':'Rendelés #',
    'calendar.title':'Naptár','calendar.pickDay':'Válasszon napot az adatok megtekintéséhez',
    'calendar.totalSold':'Összesen eladva','calendar.orders':'Rendelések','calendar.noSales':'Ezen a napon nincs eladás',
    'calendar.notes':'Megjegyzések','calendar.notesPlaceholder':'Írjon valamit erről a napról...',
    'calendar.aiAnalysis':'Nap AI elemzése','calendar.analyzeBtn':'Elemzés AI-val',
    'calendar.analyzing':'Elemzés...','calendar.today':'Ma',
    'calendar.daysWithSales':'Eladásos napok',
    'ai.title':'AI elemzés','ai.today':'ma','ai.incomeToday':'bevétel ma',
    'ai.salesToday':'Eladások ma','ai.bestDay':'Legjobb nap','ai.topProduct':'Legjobb termék',
    'ai.topProducts':'Legtöbbet eladott termékek',
    'common.save':'Mentés','common.cancel':'Mégse','common.delete':'Törlés',
    'common.loading':'Betöltés...','common.error':'Hiba','common.ok':'OK',
    'common.show':'Mutat','common.hide':'Elrejt',
    'consent.title':'Segítsen nekünk fejleszteni a Your Businesst',
    'consent.desc':'Anonim használati adatokat gyűjtünk az alkalmazás fejlesztéséhez.',
    'consent.accept':'Elfogad','consent.reject':'Nem, köszönöm',
  },
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'es')

  function t(key) {
    return T[lang]?.[key] ?? T.es[key] ?? key
  }

  function changeLang(l) {
    setLang(l)
    localStorage.setItem('lang', l)
  }

  return (
    <LanguageContext.Provider value={{ lang, t, changeLang, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useT() {
  return useContext(LanguageContext)
}
